//! RPC handlers for chat_with_data domain.
use super::{engine, sql_gen, types::*};
use serde_json::{json, Map, Value};
use tracing::debug;

pub async fn handle_register_dataset(p: Map<String, Value>) -> Result<Value, String> {
    let name = p.get("name").and_then(|v| v.as_str()).unwrap_or("unnamed");
    let source = match p.get("source").and_then(|v| v.as_str()).unwrap_or("csv") {
        "json" => DataSource::Json,
        "sqlite" => DataSource::Sqlite,
        "api" => DataSource::Api,
        _ => DataSource::Csv,
    };
    let columns: Vec<String> = p
        .get("columns")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();
    let row_count = p.get("row_count").and_then(|v| v.as_u64()).unwrap_or(0);
    let d = engine::register_dataset(name, source, columns, row_count);
    Ok(
        json!({"ok":true,"dataset_id":d.id,"name":d.name,"columns":d.columns,"row_count":d.row_count}),
    )
}

pub async fn handle_query(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    let question = p.get("question").and_then(|v| v.as_str()).unwrap_or("");

    // Get dataset schema for context.
    let ds = engine::get_dataset(id)?;

    // Try LLM-powered SQL generation for complex queries.
    let pattern_result = sql_gen::generate_sql_for_question(&ds.id, &ds.columns, question);

    if pattern_result.method == sql_gen::SqlGenMethod::Fallback {
        // Pattern matching couldn't handle it — try LLM.
        if let Some(llm_sql) = try_llm_sql_gen(&ds, question).await {
            // Validate LLM-generated SQL.
            if sql_gen::validate_sql(&llm_sql).is_ok() {
                if sql_gen::is_safe_query(&llm_sql).is_ok() {
                    let answer = format!(
                        "Generated SQL (LLM): `{}` — targeting '{}' ({} rows)",
                        llm_sql, ds.name, ds.row_count
                    );
                    return Ok(json!({
                        "ok": true, "answer": answer, "confidence": 0.85,
                        "sources": 1, "caveats": ["Generated by LLM, validated by sqlparser"],
                        "source": "llm"
                    }));
                }
            }
        }
    }

    // Use pattern-based result (or fallback).
    match engine::query_dataset(id, question) {
        Ok(r) => Ok(
            json!({"ok":true,"answer":r.answer,"confidence":r.confidence,"sources":r.sources.len(),"caveats":r.caveats,"source":"pattern"}),
        ),
        Err(e) => Ok(json!({"ok":false,"error":e})),
    }
}

/// Attempt LLM-powered SQL generation for complex queries.
async fn try_llm_sql_gen(ds: &DatasetMeta, question: &str) -> Option<String> {
    use crate::api::config::effective_backend_api_url;
    use crate::api::jwt::get_session_token;
    use crate::api::BackendOAuthClient;
    use crate::openhuman::config::ops::load_config_with_timeout;
    use reqwest::Method;

    let config = load_config_with_timeout().await.ok()?;
    let token = get_session_token(&config)
        .ok()?
        .filter(|t| !t.trim().is_empty())?;
    let api_url = effective_backend_api_url(&config.api_url);
    let client = BackendOAuthClient::new(&api_url).ok()?;

    let prompt = format!(
        "Generate a single SQL SELECT query for this question. Return ONLY the SQL, no explanation.\n\nTable: {}\nColumns: {}\nRow count: {}\n\nQuestion: {}\n\nSQL:",
        ds.id,
        ds.columns.join(", "),
        ds.row_count,
        question
    );

    let body = json!({
        "model": "agentic-v1",
        "temperature": 0.1,
        "max_tokens": 200,
        "messages": [
            {"role": "system", "content": "You are a SQL expert. Generate only valid SELECT queries. Never use DROP, DELETE, UPDATE, INSERT, ALTER, or TRUNCATE."},
            {"role": "user", "content": prompt}
        ],
    });

    let raw = client
        .authed_json(
            &token,
            Method::POST,
            "/openai/v1/chat/completions",
            Some(body),
        )
        .await
        .ok()?;

    let text = raw
        .get("choices")?
        .as_array()?
        .first()?
        .get("message")?
        .get("content")?
        .as_str()?
        .trim()
        .to_string();

    // Strip markdown code fences if present.
    let sql = text
        .strip_prefix("```sql")
        .or_else(|| text.strip_prefix("```"))
        .unwrap_or(&text)
        .strip_suffix("```")
        .unwrap_or(&text)
        .trim()
        .to_string();

    debug!(sql_len = sql.len(), "[chat_with_data] LLM SQL generated");
    Some(sql)
}

pub async fn handle_generate_insight(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    match engine::generate_insight(id) {
        Ok(i) => Ok(
            json!({"ok":true,"insight_id":i.id,"type":i.insight_type,"title":i.title,"severity":i.severity}),
        ),
        Err(e) => Ok(json!({"ok":false,"error":e})),
    }
}

pub async fn handle_list_datasets(_p: Map<String, Value>) -> Result<Value, String> {
    let all: Vec<Value> = engine::list_datasets()
        .iter()
        .map(|d| json!({"id":d.id,"name":d.name,"source":d.source,"row_count":d.row_count}))
        .collect();
    Ok(json!({"ok":true,"datasets":all}))
}

pub async fn handle_list_insights(_p: Map<String, Value>) -> Result<Value, String> {
    let all: Vec<Value> = engine::list_insights()
        .iter()
        .map(|i| json!({"id":i.id,"type":i.insight_type,"title":i.title,"severity":i.severity}))
        .collect();
    Ok(json!({"ok":true,"insights":all}))
}

pub async fn handle_get_dataset(p: Map<String, Value>) -> Result<Value, String> {
    let id = p.get("dataset_id").and_then(|v| v.as_str()).unwrap_or("");
    match engine::get_dataset(id) {
        Ok(d) => Ok(
            json!({"ok":true,"dataset_id":d.id,"name":d.name,"source":d.source,"columns":d.columns,"row_count":d.row_count}),
        ),
        Err(e) => Ok(json!({"ok":false,"error":e})),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn query_rpc() {
        let mut p = Map::new();
        p.insert("dataset_id".into(), Value::String("sample_metrics".into()));
        p.insert("question".into(), Value::String("average value".into()));
        let r = handle_query(p).await.unwrap();
        assert_eq!(r["ok"], true);
        assert!(r["answer"].as_str().unwrap().contains("AVG"));
    }
    #[tokio::test]
    async fn list_datasets_rpc() {
        let r = handle_list_datasets(Map::new()).await.unwrap();
        assert_eq!(r["ok"], true);
    }
}
